apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/harisvu9-gmail-com/pcx:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/harisvu9-gmail-com/pcx:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: pcx
        chartPath: charts/pcx
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/harisvu9-gmail-com/pcx"
          image.tag: "{{.TAG}}"
